@extends('layouts.site')
@section('meta_title','پروژه‌ها — '.($siteSettings['site_name'] ?? config('app.name')))
@section('meta_description','پروژه‌های برج مسکونی، ویلای لوکس و خانه‌های مدرن آریا سازه.')
@section('content')
<section class="projects-hero" data-parallax-scene><img class="projects-hero-image" data-parallax data-depth="10" src="{{ asset('assets/construction/hero-villa.svg') }}" alt="ویلای لوکس مدرن" width="1600" height="900" fetchpriority="high"><div class="projects-hero-shade"></div><div class="lux-container projects-hero-content reveal"><span class="breadcrumbs"><a href="{{ route('home') }}">خانه</a> / پروژه‌ها</span><h1>پروژه‌هایی فراتر از انتظار</h1><p>ترکیبی از معماری مدرن، کیفیت ماندگار و سبک زندگی لوکس در بهترین موقعیت‌های ایران.</p><div class="hero-actions"><a class="gold-btn" href="#projects-list">مشاهده پروژه‌ها ←</a><a class="glass-btn" href="{{ route('contact') }}">درخواست مشاوره</a></div></div></section>
<section class="project-filter-wrap" id="projects-list"><div class="lux-container"><form class="project-filter" method="GET"><label class="project-search"><input type="search" name="q" value="{{ request('q') }}" placeholder="جستجوی پروژه‌ها ..."><span>⌕</span></label><div class="filter-chips"><a @class(['active'=>!request('category')]) href="{{ route('projects.index') }}">همه پروژه‌ها</a>@foreach($categories as $category)<a @class(['active'=>request('category')===$category]) href="{{ route('projects.index',['category'=>$category]) }}">{{ $category }}</a>@endforeach</div><button class="filter-submit" type="submit">جستجو</button></form></div></section>
<section class="section project-listing"><div class="lux-container"><div class="listing-head"><strong>ساخت امروز، ارزش فردا</strong><span>{{ $projects->total() }} پروژه</span></div><div class="project-cards-grid">@forelse($projects as $project)@php($image=\App\Support\Media::url($project->image,'assets/construction/project-villa-01.svg'))<a class="project-list-card reveal" data-tilt href="{{ route('projects.show',$project) }}"><div class="project-list-image"><img src="{{ $image }}" alt="{{ $project->title }}" width="1000" height="650" loading="lazy"><span @class(['status-badge','done'=>$project->status==='تکمیل شده'])>{{ $project->status ?: 'در حال اجرا' }}</span></div><div class="project-list-body"><h2>{{ $project->title }}</h2><p>{{ $project->location ?: 'ایران' }}</p><div><span>{{ $project->category }}</span>@if($project->area)<span>{{ number_format($project->area) }} م²</span>@endif</div><b class="round-arrow">←</b></div></a>@empty<div class="empty-state">پروژه‌ای پیدا نشد.</div>@endforelse</div><div class="pagination-wrap">{{ $projects->links() }}</div></div></section>
@if($featured)@php($featuredImage=\App\Support\Media::url($featured->image,'assets/construction/project-tower-01.svg'))<section class="featured-project-band"><div class="lux-container featured-project-inner"><div class="featured-project-media"><img src="{{ $featuredImage }}" alt="{{ $featured->title }}" width="1000" height="650" loading="lazy"></div><div class="featured-project-copy"><span class="gold-kicker">پروژه ویژه</span><h2>{{ $featured->title }}</h2><p>{{ $featured->short_description }}</p><div class="featured-facts">@if($featured->floors)<span><b>{{ $featured->floors }}</b> طبقه</span>@endif @if($featured->units)<span><b>{{ $featured->units }}</b> واحد</span>@endif @if($featured->year)<span><b>{{ $featured->year }}</b> تحویل</span>@endif</div><a class="gold-btn" href="{{ route('projects.show',$featured) }}">مشاهده جزئیات پروژه ←</a></div></div></section>@endif
@endsection
