@extends('layouts.site')
@section('meta_title',$project->seo_title ?: $project->title.' — '.($siteSettings['site_name'] ?? config('app.name')))
@section('meta_description',$project->seo_description ?: $project->short_description)
@section('content')
@php($image=\App\Support\Media::url($project->image,'assets/construction/project-tower-01.svg'))
<section class="project-detail-hero"><div class="lux-container"><div class="project-detail-head reveal"><span class="breadcrumbs"><a href="{{ route('home') }}">خانه</a> / <a href="{{ route('projects.index') }}">پروژه‌ها</a> / {{ $project->title }}</span><span class="gold-kicker">{{ $project->category }}</span><h1>{{ $project->title }}</h1><p>{{ $project->short_description }}</p></div><div class="detail-main-image" data-parallax-scene><img data-parallax data-depth="8" src="{{ $image }}" alt="{{ $project->title }}" width="1600" height="900" fetchpriority="high"><span class="detail-status">{{ $project->status }}</span></div></div></section>
<section class="section"><div class="lux-container detail-info-grid"><aside class="project-facts reveal"><span class="gold-kicker">مشخصات پروژه</span>@if($project->location)<div><small>موقعیت</small><strong>{{ $project->location }}</strong></div>@endif @if($project->floors)<div><small>تعداد طبقات</small><strong>{{ $project->floors }} طبقه</strong></div>@endif @if($project->units)<div><small>تعداد واحد</small><strong>{{ $project->units }} واحد</strong></div>@endif @if($project->area)<div><small>زیربنای کل</small><strong>{{ number_format($project->area) }} مترمربع</strong></div>@endif @if($project->year)<div><small>سال</small><strong>{{ $project->year }}</strong></div>@endif</aside><article class="project-story reveal"><span class="gold-kicker">درباره پروژه</span><h2>معماری‌ای برای زندگی بهتر.</h2><div class="prose">{!! nl2br(e($project->body)) !!}</div><div class="story-quote">«کیفیت واقعی در جزئیاتی دیده می‌شود که سال‌ها بعد هنوز درست کار می‌کنند.»</div></article></div></section>
<section class="project-gallery"><div class="lux-container gallery-grid"><img src="{{ asset('assets/construction/hero-villa.svg') }}" alt="نمای معماری" width="1600" height="900" loading="lazy"><img src="{{ asset('assets/construction/hero-tower.svg') }}" alt="نمای برج" width="1600" height="900" loading="lazy"><img src="{{ asset('assets/construction/admin-banner.svg') }}" alt="جزئیات پروژه" width="1200" height="420" loading="lazy"></div></section>
@endsection
